export const categories = [
  {
    image: "/category/image 1.png",
    text: "Fresh Fruit",
  },
  {
    image: "/category/image 1-1.png",
    text: "Fresh Fruit",
  },
  {
    image: "/category/image 1-2.png",
    text: "Fresh Fruit",
  },
  {
    image: "/category/image 1-3.png",
    text: "Fresh Fruit",
  },
  {
    image: "/category/image 1-4.png",
    text: "Fresh Fruit",
  },
  {
    image: "/category/image 1-5.png",
    text: "Fresh Fruit",
  },
  {
    image: "/category/image 1-6.png",
    text: "Fresh Fruit",
  },
  {
    image: "/category/image 1-7.png",
    text: "Fresh Fruit",
  },
  {
    image: "/category/image 1-8.png",
    text: "Fresh Fruit",
  },
  {
    image: "/category/image 1-9.png",
    text: "Fresh Fruit",
  },
  {
    image: "/category/image 1-10.png",
    text: "Fresh Fruit",
  },
  {
    image: "/category/image 1-11.png",
    text: "Fresh Fruit",
  },
];

export const Products = [
  {
    forsale: "50% off",
    img: "/category/image 1-2.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
  {
    forsale: "50% off",
    img: "/category/image 1.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
  {
    forsale: "50% off",
    img: "/category/image 1-1.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
  {
    img: "/category/image 1-1.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
  {
    forsale: "50% off",
    img: "/category/image 1-2.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
  {
    forsale: "50% off",
    img: "/category/image 1.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
  {
    forsale: "50% off",
    img: "/category/image 1-1.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
  {
    img: "/category/image 1-1.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
  {
    forsale: "50% off",
    img: "/category/image 1-2.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
  {
    img: "/category/image 1.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
  {
    img: "/category/image 1.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
  {
    img: "/category/image 1.png",
    name: "Green Apple",
    price: "$14.99",
    oldprice: "$20.99",
    rate: 5,
  },
];

export const InstagramPost = [
  "/instagram/Instagram Post.png",
  "/instagram/Instagram Post-1.png",
  "/instagram/Instagram Post-2.png",
  "/instagram/Instagram Post-3.png",
  "/instagram/Instagram Post-4.png",
  "/instagram/Instagram Post-5.png",
];

export const faqs = [
  {
    question: "What is your return policy?",
    answer:
      "We offer a 30-day return policy on all items. Products must be in their original condition and packaging. For more details, please visit our returns page.",
  },
  {
    question: "How can I track my order?",
    answer:
      "Once your order has shipped, you will receive a tracking number via email. You can use this number to track your order on our website or through the carrier's website.",
  },
  {
    question: "Do you offer international shipping?",
    answer:
      "Yes, we offer international shipping to most countries. Shipping rates and delivery times vary depending on the destination. Please check our shipping policy for more details.",
  },
  {
    question: "What payment methods do you accept?",
    answer:
      "We accept a variety of payment methods including major credit cards (Visa, MasterCard, American Express), PayPal, and Apple Pay. For more information, visit our payment methods page.",
  },
  {
    question: "How can I contact customer support?",
    answer:
      "You can contact our customer support team via email at support@example.com, or by calling our hotline at 1-800-123-4567. Our support hours are Monday to Friday, 9 AM to 5 PM.",
  },
  {
    question: "How can I contact customer support?",
    answer:
      "You can contact our customer support team via email at support@example.com, or by calling our hotline at 1-800-123-4567. Our support hours are Monday to Friday, 9 AM to 5 PM.",
  },
];

export const categoriesShop = [
  {
    type: "Fresh Fruit",
    number: "(134)",
  },
  {
    type: "Vegetables",
    number: " (150)",
  },
  {
    type: "Cooking",
    number: " (54)",
  },
  {
    type: "Snacks",
    number: " (47)",
  },
  {
    type: "Beverages",
    number: " (43)",
  },
  {
    type: "Beauty & Health",
    number: "  (38)",
  },
  {
    type: "Bread & Bakery",
    number: "  (15)",
  },
  {
    type: "Beverages",
    number: " (43)",
  },
];

export const populartags = [
  "Healthy",
  "Low fat",
  "Vegetarian",
  "Bread",
  "Kid foods",
  "Vitamins",
  "Snacks",
  "Tiffin",
  "Meat",
  "Launch",
  "Dinner",
];
export const gallery = [""];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua &amp; Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad &amp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
